### ISSUE TITLE
destroy session on regenerate session when session is active

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-session-ext#1]
There is a use case when session already started before, and already set some value, eg: on csrf session data on a login form. When authenticate, it call the session regenerate, which session id changed, but left the old session not persisted (unset not applied as session id changed), so old session with the value remain in the disk. 

To avoid it, I think we can apply `session_destroy()` before `session_write_close()` whenever session is active. 

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-expressive-session-ext/pull/47

**Comment by weierophinney** [comment]
@michalbundyra I've added unit test for test old session destroyed first on regenerate session id on persist session.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-expressive-session-ext/pull/47#issuecomment-569059652

**Comment by weierophinney** [comment]
hm..., the test is working locally, while in travis, it still failure, I even use `@runInSeparateProcess` 

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-expressive-session-ext/pull/47#issuecomment-569061180

**Comment by weierophinney** [comment]
@michalbundyra travis green now with use custom session path in unit test, please check it.

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-expressive-session-ext/pull/47#issuecomment-569062708

**Comment by michalbundyra** [comment]
@samsonasik Fixed in 1.7.1.
