### ISSUE TITLE
Override session configuration by setting session key in config directory

### ISSUE THREAD

**Issue by krisskals** [mezzio/mezzio-session-ext#30]
### Override session configuration by setting session key in config directory

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Modify the constructor of the PhpSessionPersistence.php class to override the session configuration by setting variables in an array under the session key. Why. This would be consistent with being able to set other session parameters....

For example:

```
// file: config/autoload/session.global.php
return [
    'session' => [
		'session.name' => 'own_session_name',
		'session.cookie_secure' => true, 
		'session.cookie_httponly' = true,
		...
        'persistence' => [
            'ext' => [
                'non_locking' => true, // true|false, true => marks read_and_close as true
            ],
        ],
    ],
];
```

**Comment by Ocramius** [comment]
It is general/good practice to never do `ini_set(...)` within `laminas/` and `mezzio/` packages: they should leave the environment as they found it.

**Comment by froschdesign** [comment]
At the moment `ini_get` is used to get session configuration:

https://github.com/mezzio/mezzio-session-ext/blob/baf214e4209bc67a181d15e3bb6d1c89e46906b4/src/PhpSessionPersistence.php#L72-L91

This means that a fallback to these values is required if the application does not provide a configuration.
