### ISSUE TITLE
packagist is not auto updated

### ISSUE THREAD

**Issue by samsonasik** [mezzio/mezzio-session-ext#8]
Packagist currently seems not auto updated. @weierophinney could you check? thank you.

**Comment by michalbundyra** [comment]
@samsonasik What's the issue? The latest version is 1.7.0 and I can see it on packagist.

**Comment by samsonasik** [comment]
yes, but if new version is pushed in the future, we will need manually click "update" in packagist site

**Comment by weierophinney** [comment]
Odd - I enabled packagist on all orgs on Friday. I'll double check tomorrow.

**Comment by weierophinney** [comment]
Resolved for all laminas-api-tools and mezzio packages (laminas packages were already fine).
